namespace SVNMonitor.View.Dialogs
{
	internal partial class SettingsDialog
	{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}

		#region Windows Form Designer generated code
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(SettingsDialog));
			btnOK = new System.Windows.Forms.Button();
			btnCancel = new System.Windows.Forms.Button();
			uiTabs = new Janus.Windows.UI.Tab.UITab();
			uiTabPageGeneral = new Janus.Windows.UI.Tab.UITabPage();
			label13 = new System.Windows.Forms.Label();
			checkStartWithWindows = new System.Windows.Forms.CheckBox();
			checkStartMinimized = new System.Windows.Forms.CheckBox();
			checkHideWhenMinimized = new System.Windows.Forms.CheckBox();
			checkMinimizeWhenClosing = new System.Windows.Forms.CheckBox();
			uiTabPageDisplay = new Janus.Windows.UI.Tab.UITabPage();
			checkShowDefaultTextInsteadOfEmptyLogMessage = new System.Windows.Forms.CheckBox();
			groupSourcesPanel = new System.Windows.Forms.GroupBox();
			checkSourcesPanelShowPath = new System.Windows.Forms.CheckBox();
			checkSourcesPanelShowNoUpdates = new System.Windows.Forms.CheckBox();
			checkSourcesPanelShowLastCheck = new System.Windows.Forms.CheckBox();
			checkSourcesPanelShowUrl = new System.Windows.Forms.CheckBox();
			label14 = new System.Windows.Forms.Label();
			numPreviewLines = new System.Windows.Forms.NumericUpDown();
			checkUnlimitedPageSize = new System.Windows.Forms.CheckBox();
			label8 = new System.Windows.Forms.Label();
			label4 = new System.Windows.Forms.Label();
			label10 = new System.Windows.Forms.Label();
			numPageSize = new System.Windows.Forms.NumericUpDown();
			uiTabPageOperation = new Janus.Windows.UI.Tab.UITabPage();
			linkTextEditorBrowse = new System.Windows.Forms.LinkLabel();
			checkDismissErrorsWhenClicked = new System.Windows.Forms.CheckBox();
			checkPromptUpdateHeadRevision = new System.Windows.Forms.CheckBox();
			checkPromptUpdateOldRevision = new System.Windows.Forms.CheckBox();
			label15 = new System.Windows.Forms.Label();
			txtTextEditor = new System.Windows.Forms.TextBox();
			label11 = new System.Windows.Forms.Label();
			comboDefaultUserAction = new System.Windows.Forms.ComboBox();
			label6 = new System.Windows.Forms.Label();
			uiTabPageKeyboard = new Janus.Windows.UI.Tab.UITabPage();
			keyboardEditor1 = new SVNMonitor.View.Controls.KeyboardEditor();
			label16 = new System.Windows.Forms.Label();
			uiTabPageUpdates = new Janus.Windows.UI.Tab.UITabPage();
			lblWatchTheNetworkAvailability = new System.Windows.Forms.Label();
			label17 = new System.Windows.Forms.Label();
			checkWatchTheNetworkAvailability = new System.Windows.Forms.CheckBox();
			checkIgnoreIgnoreOnCommitConflicts = new System.Windows.Forms.CheckBox();
			checkIgnoreIgnoreOnCommit = new System.Windows.Forms.CheckBox();
			label1 = new System.Windows.Forms.Label();
			checkTreatUnversionedAsModified = new System.Windows.Forms.CheckBox();
			checkEnableUpdates = new System.Windows.Forms.CheckBox();
			checkAutomaticInterval = new System.Windows.Forms.CheckBox();
			numSecondsPerSource = new System.Windows.Forms.NumericUpDown();
			numUpdatesInterval = new System.Windows.Forms.NumericUpDown();
			label2 = new System.Windows.Forms.Label();
			uiTabPageTortoiseSVN = new Janus.Windows.UI.Tab.UITabPage();
			linkTortoiseEXEBrowse = new System.Windows.Forms.LinkLabel();
			checkAutomaticallyResolveTortoiseSVNProcess = new System.Windows.Forms.CheckBox();
			numSVNUpdateSourcesQueueTimeoutSeconds = new System.Windows.Forms.NumericUpDown();
			label9 = new System.Windows.Forms.Label();
			checkSVNUpdateSourcesParallel = new System.Windows.Forms.CheckBox();
			checkIgnoreDisabledSourcesWhenUpdatingAll = new System.Windows.Forms.CheckBox();
			cmdTortoiseSVNSettings = new System.Windows.Forms.Button();
			label18 = new System.Windows.Forms.Label();
			comboAutoCloseTortoiseSVN = new System.Windows.Forms.ComboBox();
			label5 = new System.Windows.Forms.Label();
			linkAutoCheckTortoiseSVN = new System.Windows.Forms.LinkLabel();
			label3 = new System.Windows.Forms.Label();
			txtTortoiseEXE = new System.Windows.Forms.TextBox();
			uiTabPageRecommending = new Janus.Windows.UI.Tab.UITabPage();
			uiGroupBoxRecommendMessage = new System.Windows.Forms.GroupBox();
			txtRecommendMessage = new System.Windows.Forms.TextBox();
			label19 = new System.Windows.Forms.Label();
			label22 = new System.Windows.Forms.Label();
			label21 = new System.Windows.Forms.Label();
			uiTabPageVersionCheck = new Janus.Windows.UI.Tab.UITabPage();
			groupVersionChecks = new System.Windows.Forms.GroupBox();
			lblEnableVersionUpgrade = new System.Windows.Forms.Label();
			checkSendUsageInformation = new System.Windows.Forms.CheckBox();
			label7 = new System.Windows.Forms.Label();
			checkEnableVersionUpgrade = new System.Windows.Forms.CheckBox();
			numVersionCheckInterval = new System.Windows.Forms.NumericUpDown();
			checkVersionCheckAtStartup = new System.Windows.Forms.CheckBox();
			label20 = new System.Windows.Forms.Label();
			checkEnableVersionCheck = new System.Windows.Forms.CheckBox();
			panelBottom = new System.Windows.Forms.Panel();
			treeView1 = new System.Windows.Forms.TreeView();
			panelLeft = new System.Windows.Forms.Panel();
			panelRight = new System.Windows.Forms.Panel();
			checkCommitIsAlwaysEnabled = new System.Windows.Forms.CheckBox();
			((System.ComponentModel.ISupportInitialize)uiTabs).BeginInit();
			uiTabs.SuspendLayout();
			uiTabPageGeneral.SuspendLayout();
			uiTabPageDisplay.SuspendLayout();
			groupSourcesPanel.SuspendLayout();
			numPreviewLines.BeginInit();
			numPageSize.BeginInit();
			uiTabPageOperation.SuspendLayout();
			uiTabPageKeyboard.SuspendLayout();
			uiTabPageUpdates.SuspendLayout();
			numSecondsPerSource.BeginInit();
			numUpdatesInterval.BeginInit();
			uiTabPageTortoiseSVN.SuspendLayout();
			numSVNUpdateSourcesQueueTimeoutSeconds.BeginInit();
			uiTabPageRecommending.SuspendLayout();
			uiGroupBoxRecommendMessage.SuspendLayout();
			uiTabPageVersionCheck.SuspendLayout();
			groupVersionChecks.SuspendLayout();
			numVersionCheckInterval.BeginInit();
			panelBottom.SuspendLayout();
			panelLeft.SuspendLayout();
			panelRight.SuspendLayout();
			base.SuspendLayout();
			resources.ApplyResources(btnOK, "btnOK");
			btnOK.DialogResult = System.Windows.Forms.DialogResult.OK;
			btnOK.Name = "btnOK";
			btnOK.Click += btnOK_Click;
			resources.ApplyResources(btnCancel, "btnCancel");
			btnCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
			btnCancel.Name = "btnCancel";
			uiTabs.BackColor = System.Drawing.Color.Transparent;
			resources.ApplyResources(uiTabs, "uiTabs");
			uiTabs.Name = "uiTabs";
			uiTabs.ShowFocusRectangle = false;
			uiTabs.TabPages.AddRange(new Janus.Windows.UI.Tab.UITabPage[]
			{
				uiTabPageGeneral, uiTabPageDisplay, uiTabPageOperation, uiTabPageKeyboard, uiTabPageUpdates, uiTabPageTortoiseSVN, uiTabPageRecommending, uiTabPageVersionCheck
			});
			uiTabs.TabStop = false;
			uiTabs.VisualStyle = Janus.Windows.UI.Tab.TabVisualStyle.VS2005;
			uiTabPageGeneral.Controls.Add(label13);
			uiTabPageGeneral.Controls.Add(checkStartWithWindows);
			uiTabPageGeneral.Controls.Add(checkStartMinimized);
			uiTabPageGeneral.Controls.Add(checkHideWhenMinimized);
			uiTabPageGeneral.Controls.Add(checkMinimizeWhenClosing);
			uiTabPageGeneral.Key = "General";
			resources.ApplyResources(uiTabPageGeneral, "uiTabPageGeneral");
			uiTabPageGeneral.Name = "uiTabPageGeneral";
			uiTabPageGeneral.TabStop = true;
			label13.BackColor = System.Drawing.Color.DimGray;
			label13.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			resources.ApplyResources(label13, "label13");
			label13.ForeColor = System.Drawing.Color.White;
			label13.Name = "label13";
			resources.ApplyResources(checkStartWithWindows, "checkStartWithWindows");
			checkStartWithWindows.BackColor = System.Drawing.Color.Transparent;
			checkStartWithWindows.Checked = true;
			checkStartWithWindows.CheckState = System.Windows.Forms.CheckState.Checked;
			checkStartWithWindows.Name = "checkStartWithWindows";
			checkStartWithWindows.UseVisualStyleBackColor = true;
			resources.ApplyResources(checkStartMinimized, "checkStartMinimized");
			checkStartMinimized.BackColor = System.Drawing.Color.Transparent;
			checkStartMinimized.Checked = true;
			checkStartMinimized.CheckState = System.Windows.Forms.CheckState.Checked;
			checkStartMinimized.Name = "checkStartMinimized";
			checkStartMinimized.UseVisualStyleBackColor = true;
			resources.ApplyResources(checkHideWhenMinimized, "checkHideWhenMinimized");
			checkHideWhenMinimized.BackColor = System.Drawing.Color.Transparent;
			checkHideWhenMinimized.Checked = true;
			checkHideWhenMinimized.CheckState = System.Windows.Forms.CheckState.Checked;
			checkHideWhenMinimized.Name = "checkHideWhenMinimized";
			checkHideWhenMinimized.UseVisualStyleBackColor = true;
			resources.ApplyResources(checkMinimizeWhenClosing, "checkMinimizeWhenClosing");
			checkMinimizeWhenClosing.BackColor = System.Drawing.Color.Transparent;
			checkMinimizeWhenClosing.Checked = true;
			checkMinimizeWhenClosing.CheckState = System.Windows.Forms.CheckState.Checked;
			checkMinimizeWhenClosing.Name = "checkMinimizeWhenClosing";
			checkMinimizeWhenClosing.UseVisualStyleBackColor = true;
			uiTabPageDisplay.Controls.Add(checkShowDefaultTextInsteadOfEmptyLogMessage);
			uiTabPageDisplay.Controls.Add(groupSourcesPanel);
			uiTabPageDisplay.Controls.Add(label14);
			uiTabPageDisplay.Controls.Add(numPreviewLines);
			uiTabPageDisplay.Controls.Add(checkUnlimitedPageSize);
			uiTabPageDisplay.Controls.Add(label8);
			uiTabPageDisplay.Controls.Add(label4);
			uiTabPageDisplay.Controls.Add(label10);
			uiTabPageDisplay.Controls.Add(numPageSize);
			uiTabPageDisplay.Key = "Display";
			resources.ApplyResources(uiTabPageDisplay, "uiTabPageDisplay");
			uiTabPageDisplay.Name = "uiTabPageDisplay";
			uiTabPageDisplay.TabStop = true;
			resources.ApplyResources(checkShowDefaultTextInsteadOfEmptyLogMessage, "checkShowDefaultTextInsteadOfEmptyLogMessage");
			checkShowDefaultTextInsteadOfEmptyLogMessage.BackColor = System.Drawing.Color.Transparent;
			checkShowDefaultTextInsteadOfEmptyLogMessage.Checked = true;
			checkShowDefaultTextInsteadOfEmptyLogMessage.CheckState = System.Windows.Forms.CheckState.Checked;
			checkShowDefaultTextInsteadOfEmptyLogMessage.Name = "checkShowDefaultTextInsteadOfEmptyLogMessage";
			checkShowDefaultTextInsteadOfEmptyLogMessage.UseVisualStyleBackColor = true;
			resources.ApplyResources(groupSourcesPanel, "groupSourcesPanel");
			groupSourcesPanel.BackColor = System.Drawing.Color.Transparent;
			groupSourcesPanel.Controls.Add(checkSourcesPanelShowPath);
			groupSourcesPanel.Controls.Add(checkSourcesPanelShowNoUpdates);
			groupSourcesPanel.Controls.Add(checkSourcesPanelShowLastCheck);
			groupSourcesPanel.Controls.Add(checkSourcesPanelShowUrl);
			groupSourcesPanel.Name = "groupSourcesPanel";
			groupSourcesPanel.TabStop = false;
			resources.ApplyResources(checkSourcesPanelShowPath, "checkSourcesPanelShowPath");
			checkSourcesPanelShowPath.Name = "checkSourcesPanelShowPath";
			checkSourcesPanelShowPath.UseVisualStyleBackColor = true;
			resources.ApplyResources(checkSourcesPanelShowNoUpdates, "checkSourcesPanelShowNoUpdates");
			checkSourcesPanelShowNoUpdates.Name = "checkSourcesPanelShowNoUpdates";
			checkSourcesPanelShowNoUpdates.UseVisualStyleBackColor = true;
			resources.ApplyResources(checkSourcesPanelShowLastCheck, "checkSourcesPanelShowLastCheck");
			checkSourcesPanelShowLastCheck.Name = "checkSourcesPanelShowLastCheck";
			checkSourcesPanelShowLastCheck.UseVisualStyleBackColor = true;
			resources.ApplyResources(checkSourcesPanelShowUrl, "checkSourcesPanelShowUrl");
			checkSourcesPanelShowUrl.Name = "checkSourcesPanelShowUrl";
			checkSourcesPanelShowUrl.UseVisualStyleBackColor = true;
			label14.BackColor = System.Drawing.Color.DimGray;
			label14.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			resources.ApplyResources(label14, "label14");
			label14.ForeColor = System.Drawing.Color.White;
			label14.Name = "label14";
			resources.ApplyResources(numPreviewLines, "numPreviewLines");
			int[] tempAnotherLocal1 = new int[4];
			tempAnotherLocal1[0] = 0xf423f;
			numPreviewLines.Maximum = new decimal(tempAnotherLocal1);
			int[] tempAnotherLocal2 = new int[4];
			tempAnotherLocal2[0] = 1;
			numPreviewLines.Minimum = new decimal(tempAnotherLocal2);
			numPreviewLines.Name = "numPreviewLines";
			int[] tempAnotherLocal3 = new int[4];
			tempAnotherLocal3[0] = 1;
			numPreviewLines.Value = new decimal(tempAnotherLocal3);
			resources.ApplyResources(checkUnlimitedPageSize, "checkUnlimitedPageSize");
			checkUnlimitedPageSize.BackColor = System.Drawing.Color.Transparent;
			checkUnlimitedPageSize.Checked = true;
			checkUnlimitedPageSize.CheckState = System.Windows.Forms.CheckState.Checked;
			checkUnlimitedPageSize.Name = "checkUnlimitedPageSize";
			checkUnlimitedPageSize.UseVisualStyleBackColor = true;
			checkUnlimitedPageSize.CheckedChanged += checkUnlimitedPageSize_CheckedChanged;
			resources.ApplyResources(label8, "label8");
			label8.BackColor = System.Drawing.Color.Transparent;
			label8.ForeColor = System.Drawing.Color.MidnightBlue;
			label8.Name = "label8";
			resources.ApplyResources(label4, "label4");
			label4.BackColor = System.Drawing.Color.Transparent;
			label4.Name = "label4";
			resources.ApplyResources(label10, "label10");
			label10.BackColor = System.Drawing.Color.Transparent;
			label10.Name = "label10";
			resources.ApplyResources(numPageSize, "numPageSize");
			int[] tempAnotherLocal4 = new int[4];
			tempAnotherLocal4[0] = 0xf423f;
			numPageSize.Maximum = new decimal(tempAnotherLocal4);
			int[] tempAnotherLocal5 = new int[4];
			tempAnotherLocal5[0] = 1;
			numPageSize.Minimum = new decimal(tempAnotherLocal5);
			numPageSize.Name = "numPageSize";
			int[] tempAnotherLocal6 = new int[4];
			tempAnotherLocal6[0] = 1;
			numPageSize.Value = new decimal(tempAnotherLocal6);
			uiTabPageOperation.Controls.Add(checkCommitIsAlwaysEnabled);
			uiTabPageOperation.Controls.Add(linkTextEditorBrowse);
			uiTabPageOperation.Controls.Add(checkDismissErrorsWhenClicked);
			uiTabPageOperation.Controls.Add(checkPromptUpdateHeadRevision);
			uiTabPageOperation.Controls.Add(checkPromptUpdateOldRevision);
			uiTabPageOperation.Controls.Add(label15);
			uiTabPageOperation.Controls.Add(txtTextEditor);
			uiTabPageOperation.Controls.Add(label11);
			uiTabPageOperation.Controls.Add(comboDefaultUserAction);
			uiTabPageOperation.Controls.Add(label6);
			uiTabPageOperation.Key = "Operation";
			resources.ApplyResources(uiTabPageOperation, "uiTabPageOperation");
			uiTabPageOperation.Name = "uiTabPageOperation";
			uiTabPageOperation.TabStop = true;
			resources.ApplyResources(linkTextEditorBrowse, "linkTextEditorBrowse");
			linkTextEditorBrowse.BackColor = System.Drawing.Color.Transparent;
			linkTextEditorBrowse.Name = "linkTextEditorBrowse";
			linkTextEditorBrowse.TabStop = true;
			linkTextEditorBrowse.LinkClicked += linkTextEditorBrowse_LinkClicked;
			resources.ApplyResources(checkDismissErrorsWhenClicked, "checkDismissErrorsWhenClicked");
			checkDismissErrorsWhenClicked.BackColor = System.Drawing.Color.Transparent;
			checkDismissErrorsWhenClicked.Checked = true;
			checkDismissErrorsWhenClicked.CheckState = System.Windows.Forms.CheckState.Checked;
			checkDismissErrorsWhenClicked.Name = "checkDismissErrorsWhenClicked";
			checkDismissErrorsWhenClicked.UseVisualStyleBackColor = true;
			resources.ApplyResources(checkPromptUpdateHeadRevision, "checkPromptUpdateHeadRevision");
			checkPromptUpdateHeadRevision.BackColor = System.Drawing.Color.Transparent;
			checkPromptUpdateHeadRevision.Checked = true;
			checkPromptUpdateHeadRevision.CheckState = System.Windows.Forms.CheckState.Checked;
			checkPromptUpdateHeadRevision.Name = "checkPromptUpdateHeadRevision";
			checkPromptUpdateHeadRevision.UseVisualStyleBackColor = true;
			resources.ApplyResources(checkPromptUpdateOldRevision, "checkPromptUpdateOldRevision");
			checkPromptUpdateOldRevision.BackColor = System.Drawing.Color.Transparent;
			checkPromptUpdateOldRevision.Checked = true;
			checkPromptUpdateOldRevision.CheckState = System.Windows.Forms.CheckState.Checked;
			checkPromptUpdateOldRevision.Name = "checkPromptUpdateOldRevision";
			checkPromptUpdateOldRevision.UseVisualStyleBackColor = true;
			label15.BackColor = System.Drawing.Color.DimGray;
			label15.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			resources.ApplyResources(label15, "label15");
			label15.ForeColor = System.Drawing.Color.White;
			label15.Name = "label15";
			resources.ApplyResources(txtTextEditor, "txtTextEditor");
			txtTextEditor.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.SuggestAppend;
			txtTextEditor.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.FileSystem;
			txtTextEditor.Name = "txtTextEditor";
			resources.ApplyResources(label11, "label11");
			label11.BackColor = System.Drawing.Color.Transparent;
			label11.Name = "label11";
			resources.ApplyResources(comboDefaultUserAction, "comboDefaultUserAction");
			comboDefaultUserAction.DisplayMember = "Description";
			comboDefaultUserAction.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
			comboDefaultUserAction.Name = "comboDefaultUserAction";
			comboDefaultUserAction.ValueMember = "Value";
			resources.ApplyResources(label6, "label6");
			label6.BackColor = System.Drawing.Color.Transparent;
			label6.Name = "label6";
			uiTabPageKeyboard.Controls.Add(keyboardEditor1);
			uiTabPageKeyboard.Controls.Add(label16);
			uiTabPageKeyboard.Key = "Keyboard";
			resources.ApplyResources(uiTabPageKeyboard, "uiTabPageKeyboard");
			uiTabPageKeyboard.Name = "uiTabPageKeyboard";
			uiTabPageKeyboard.TabStop = true;
			keyboardEditor1.BackColor = System.Drawing.Color.Transparent;
			resources.ApplyResources(keyboardEditor1, "keyboardEditor1");
			keyboardEditor1.Name = "keyboardEditor1";
			label16.BackColor = System.Drawing.Color.DimGray;
			label16.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			resources.ApplyResources(label16, "label16");
			label16.ForeColor = System.Drawing.Color.White;
			label16.Name = "label16";
			uiTabPageUpdates.Controls.Add(lblWatchTheNetworkAvailability);
			uiTabPageUpdates.Controls.Add(label17);
			uiTabPageUpdates.Controls.Add(checkWatchTheNetworkAvailability);
			uiTabPageUpdates.Controls.Add(checkIgnoreIgnoreOnCommitConflicts);
			uiTabPageUpdates.Controls.Add(checkIgnoreIgnoreOnCommit);
			uiTabPageUpdates.Controls.Add(label1);
			uiTabPageUpdates.Controls.Add(checkTreatUnversionedAsModified);
			uiTabPageUpdates.Controls.Add(checkEnableUpdates);
			uiTabPageUpdates.Controls.Add(checkAutomaticInterval);
			uiTabPageUpdates.Controls.Add(numSecondsPerSource);
			uiTabPageUpdates.Controls.Add(numUpdatesInterval);
			uiTabPageUpdates.Controls.Add(label2);
			uiTabPageUpdates.Key = "Sources";
			resources.ApplyResources(uiTabPageUpdates, "uiTabPageUpdates");
			uiTabPageUpdates.Name = "uiTabPageUpdates";
			uiTabPageUpdates.TabStop = true;
			resources.ApplyResources(lblWatchTheNetworkAvailability, "lblWatchTheNetworkAvailability");
			lblWatchTheNetworkAvailability.BackColor = System.Drawing.Color.Transparent;
			lblWatchTheNetworkAvailability.ForeColor = System.Drawing.Color.MidnightBlue;
			lblWatchTheNetworkAvailability.Name = "lblWatchTheNetworkAvailability";
			label17.BackColor = System.Drawing.Color.DimGray;
			label17.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			resources.ApplyResources(label17, "label17");
			label17.ForeColor = System.Drawing.Color.White;
			label17.Name = "label17";
			resources.ApplyResources(checkWatchTheNetworkAvailability, "checkWatchTheNetworkAvailability");
			checkWatchTheNetworkAvailability.BackColor = System.Drawing.Color.Transparent;
			checkWatchTheNetworkAvailability.Checked = true;
			checkWatchTheNetworkAvailability.CheckState = System.Windows.Forms.CheckState.Checked;
			checkWatchTheNetworkAvailability.Name = "checkWatchTheNetworkAvailability";
			checkWatchTheNetworkAvailability.UseVisualStyleBackColor = true;
			resources.ApplyResources(checkIgnoreIgnoreOnCommitConflicts, "checkIgnoreIgnoreOnCommitConflicts");
			checkIgnoreIgnoreOnCommitConflicts.BackColor = System.Drawing.Color.Transparent;
			checkIgnoreIgnoreOnCommitConflicts.Checked = true;
			checkIgnoreIgnoreOnCommitConflicts.CheckState = System.Windows.Forms.CheckState.Checked;
			checkIgnoreIgnoreOnCommitConflicts.Name = "checkIgnoreIgnoreOnCommitConflicts";
			checkIgnoreIgnoreOnCommitConflicts.UseVisualStyleBackColor = true;
			resources.ApplyResources(checkIgnoreIgnoreOnCommit, "checkIgnoreIgnoreOnCommit");
			checkIgnoreIgnoreOnCommit.BackColor = System.Drawing.Color.Transparent;
			checkIgnoreIgnoreOnCommit.Checked = true;
			checkIgnoreIgnoreOnCommit.CheckState = System.Windows.Forms.CheckState.Checked;
			checkIgnoreIgnoreOnCommit.Name = "checkIgnoreIgnoreOnCommit";
			checkIgnoreIgnoreOnCommit.UseVisualStyleBackColor = true;
			resources.ApplyResources(label1, "label1");
			label1.BackColor = System.Drawing.Color.Transparent;
			label1.ForeColor = System.Drawing.Color.MidnightBlue;
			label1.Name = "label1";
			resources.ApplyResources(checkTreatUnversionedAsModified, "checkTreatUnversionedAsModified");
			checkTreatUnversionedAsModified.BackColor = System.Drawing.Color.Transparent;
			checkTreatUnversionedAsModified.Checked = true;
			checkTreatUnversionedAsModified.CheckState = System.Windows.Forms.CheckState.Checked;
			checkTreatUnversionedAsModified.Name = "checkTreatUnversionedAsModified";
			checkTreatUnversionedAsModified.UseVisualStyleBackColor = true;
			resources.ApplyResources(checkEnableUpdates, "checkEnableUpdates");
			checkEnableUpdates.BackColor = System.Drawing.Color.Transparent;
			checkEnableUpdates.Checked = true;
			checkEnableUpdates.CheckState = System.Windows.Forms.CheckState.Checked;
			checkEnableUpdates.Name = "checkEnableUpdates";
			checkEnableUpdates.UseVisualStyleBackColor = true;
			resources.ApplyResources(checkAutomaticInterval, "checkAutomaticInterval");
			checkAutomaticInterval.BackColor = System.Drawing.Color.Transparent;
			checkAutomaticInterval.Checked = true;
			checkAutomaticInterval.CheckState = System.Windows.Forms.CheckState.Checked;
			checkAutomaticInterval.Name = "checkAutomaticInterval";
			checkAutomaticInterval.UseVisualStyleBackColor = true;
			checkAutomaticInterval.CheckedChanged += checkAutomaticInterval_CheckedChanged;
			resources.ApplyResources(numSecondsPerSource, "numSecondsPerSource");
			int[] tempAnotherLocal7 = new int[4];
			tempAnotherLocal7[0] = 0xe10;
			numSecondsPerSource.Maximum = new decimal(tempAnotherLocal7);
			int[] tempAnotherLocal8 = new int[4];
			tempAnotherLocal8[0] = 1;
			numSecondsPerSource.Minimum = new decimal(tempAnotherLocal8);
			numSecondsPerSource.Name = "numSecondsPerSource";
			int[] tempAnotherLocal9 = new int[4];
			tempAnotherLocal9[0] = 1;
			numSecondsPerSource.Value = new decimal(tempAnotherLocal9);
			resources.ApplyResources(numUpdatesInterval, "numUpdatesInterval");
			int[] tempAnotherLocal10 = new int[4];
			tempAnotherLocal10[0] = 0x5a0;
			numUpdatesInterval.Maximum = new decimal(tempAnotherLocal10);
			numUpdatesInterval.Name = "numUpdatesInterval";
			resources.ApplyResources(label2, "label2");
			label2.BackColor = System.Drawing.Color.Transparent;
			label2.Name = "label2";
			uiTabPageTortoiseSVN.Controls.Add(linkTortoiseEXEBrowse);
			uiTabPageTortoiseSVN.Controls.Add(checkAutomaticallyResolveTortoiseSVNProcess);
			uiTabPageTortoiseSVN.Controls.Add(numSVNUpdateSourcesQueueTimeoutSeconds);
			uiTabPageTortoiseSVN.Controls.Add(label9);
			uiTabPageTortoiseSVN.Controls.Add(checkSVNUpdateSourcesParallel);
			uiTabPageTortoiseSVN.Controls.Add(checkIgnoreDisabledSourcesWhenUpdatingAll);
			uiTabPageTortoiseSVN.Controls.Add(cmdTortoiseSVNSettings);
			uiTabPageTortoiseSVN.Controls.Add(label18);
			uiTabPageTortoiseSVN.Controls.Add(comboAutoCloseTortoiseSVN);
			uiTabPageTortoiseSVN.Controls.Add(label5);
			uiTabPageTortoiseSVN.Controls.Add(linkAutoCheckTortoiseSVN);
			uiTabPageTortoiseSVN.Controls.Add(label3);
			uiTabPageTortoiseSVN.Controls.Add(txtTortoiseEXE);
			uiTabPageTortoiseSVN.Key = "TortoiseSVN";
			resources.ApplyResources(uiTabPageTortoiseSVN, "uiTabPageTortoiseSVN");
			uiTabPageTortoiseSVN.Name = "uiTabPageTortoiseSVN";
			uiTabPageTortoiseSVN.TabStop = true;
			resources.ApplyResources(linkTortoiseEXEBrowse, "linkTortoiseEXEBrowse");
			linkTortoiseEXEBrowse.BackColor = System.Drawing.Color.Transparent;
			linkTortoiseEXEBrowse.Name = "linkTortoiseEXEBrowse";
			linkTortoiseEXEBrowse.TabStop = true;
			linkTortoiseEXEBrowse.LinkClicked += linkTortoiseEXEBrowse_LinkClicked;
			resources.ApplyResources(checkAutomaticallyResolveTortoiseSVNProcess, "checkAutomaticallyResolveTortoiseSVNProcess");
			checkAutomaticallyResolveTortoiseSVNProcess.BackColor = System.Drawing.Color.Transparent;
			checkAutomaticallyResolveTortoiseSVNProcess.Checked = true;
			checkAutomaticallyResolveTortoiseSVNProcess.CheckState = System.Windows.Forms.CheckState.Checked;
			checkAutomaticallyResolveTortoiseSVNProcess.Name = "checkAutomaticallyResolveTortoiseSVNProcess";
			checkAutomaticallyResolveTortoiseSVNProcess.UseVisualStyleBackColor = true;
			checkAutomaticallyResolveTortoiseSVNProcess.CheckedChanged += checkAutomaticallyResolveTortoiseSVNProcess_CheckedChanged;
			resources.ApplyResources(numSVNUpdateSourcesQueueTimeoutSeconds, "numSVNUpdateSourcesQueueTimeoutSeconds");
			int[] tempAnotherLocal11 = new int[4];
			tempAnotherLocal11[0] = 300;
			numSVNUpdateSourcesQueueTimeoutSeconds.Maximum = new decimal(tempAnotherLocal11);
			int[] tempAnotherLocal12 = new int[4];
			tempAnotherLocal12[0] = 1;
			numSVNUpdateSourcesQueueTimeoutSeconds.Minimum = new decimal(tempAnotherLocal12);
			numSVNUpdateSourcesQueueTimeoutSeconds.Name = "numSVNUpdateSourcesQueueTimeoutSeconds";
			int[] tempAnotherLocal13 = new int[4];
			tempAnotherLocal13[0] = 1;
			numSVNUpdateSourcesQueueTimeoutSeconds.Value = new decimal(tempAnotherLocal13);
			resources.ApplyResources(label9, "label9");
			label9.BackColor = System.Drawing.Color.Transparent;
			label9.Name = "label9";
			resources.ApplyResources(checkSVNUpdateSourcesParallel, "checkSVNUpdateSourcesParallel");
			checkSVNUpdateSourcesParallel.BackColor = System.Drawing.Color.Transparent;
			checkSVNUpdateSourcesParallel.Checked = true;
			checkSVNUpdateSourcesParallel.CheckState = System.Windows.Forms.CheckState.Checked;
			checkSVNUpdateSourcesParallel.Name = "checkSVNUpdateSourcesParallel";
			checkSVNUpdateSourcesParallel.UseVisualStyleBackColor = true;
			checkSVNUpdateSourcesParallel.CheckedChanged += checkSVNUpdateSourcesParallel_CheckedChanged;
			resources.ApplyResources(checkIgnoreDisabledSourcesWhenUpdatingAll, "checkIgnoreDisabledSourcesWhenUpdatingAll");
			checkIgnoreDisabledSourcesWhenUpdatingAll.BackColor = System.Drawing.Color.Transparent;
			checkIgnoreDisabledSourcesWhenUpdatingAll.Checked = true;
			checkIgnoreDisabledSourcesWhenUpdatingAll.CheckState = System.Windows.Forms.CheckState.Checked;
			checkIgnoreDisabledSourcesWhenUpdatingAll.Name = "checkIgnoreDisabledSourcesWhenUpdatingAll";
			checkIgnoreDisabledSourcesWhenUpdatingAll.UseVisualStyleBackColor = true;
			resources.ApplyResources(cmdTortoiseSVNSettings, "cmdTortoiseSVNSettings");
			cmdTortoiseSVNSettings.Name = "cmdTortoiseSVNSettings";
			cmdTortoiseSVNSettings.Click += cmdTortoiseSVNSettings_Click;
			label18.BackColor = System.Drawing.Color.DimGray;
			label18.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			resources.ApplyResources(label18, "label18");
			label18.ForeColor = System.Drawing.Color.White;
			label18.Name = "label18";
			resources.ApplyResources(comboAutoCloseTortoiseSVN, "comboAutoCloseTortoiseSVN");
			comboAutoCloseTortoiseSVN.DisplayMember = "Description";
			comboAutoCloseTortoiseSVN.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
			comboAutoCloseTortoiseSVN.Name = "comboAutoCloseTortoiseSVN";
			comboAutoCloseTortoiseSVN.ValueMember = "Value";
			resources.ApplyResources(label5, "label5");
			label5.BackColor = System.Drawing.Color.Transparent;
			label5.Name = "label5";
			resources.ApplyResources(linkAutoCheckTortoiseSVN, "linkAutoCheckTortoiseSVN");
			linkAutoCheckTortoiseSVN.BackColor = System.Drawing.Color.Transparent;
			linkAutoCheckTortoiseSVN.Name = "linkAutoCheckTortoiseSVN";
			linkAutoCheckTortoiseSVN.TabStop = true;
			linkAutoCheckTortoiseSVN.LinkClicked += linkAutoCheckTortoiseSVN_LinkClicked;
			resources.ApplyResources(label3, "label3");
			label3.BackColor = System.Drawing.Color.Transparent;
			label3.Name = "label3";
			resources.ApplyResources(txtTortoiseEXE, "txtTortoiseEXE");
			txtTortoiseEXE.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.SuggestAppend;
			txtTortoiseEXE.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.FileSystem;
			txtTortoiseEXE.Name = "txtTortoiseEXE";
			txtTortoiseEXE.Enter += txtTortoiseEXE_Enter;
			uiTabPageRecommending.Controls.Add(uiGroupBoxRecommendMessage);
			uiTabPageRecommending.Controls.Add(label22);
			uiTabPageRecommending.Controls.Add(label21);
			uiTabPageRecommending.Key = "Recommending";
			resources.ApplyResources(uiTabPageRecommending, "uiTabPageRecommending");
			uiTabPageRecommending.Name = "uiTabPageRecommending";
			uiTabPageRecommending.TabStop = true;
			resources.ApplyResources(uiGroupBoxRecommendMessage, "uiGroupBoxRecommendMessage");
			uiGroupBoxRecommendMessage.BackColor = System.Drawing.Color.Transparent;
			uiGroupBoxRecommendMessage.Controls.Add(txtRecommendMessage);
			uiGroupBoxRecommendMessage.Controls.Add(label19);
			uiGroupBoxRecommendMessage.Name = "uiGroupBoxRecommendMessage";
			uiGroupBoxRecommendMessage.TabStop = false;
			resources.ApplyResources(txtRecommendMessage, "txtRecommendMessage");
			txtRecommendMessage.Name = "txtRecommendMessage";
			resources.ApplyResources(label19, "label19");
			label19.BackColor = System.Drawing.Color.Transparent;
			label19.ForeColor = System.Drawing.Color.MidnightBlue;
			label19.Name = "label19";
			resources.ApplyResources(label22, "label22");
			label22.BackColor = System.Drawing.Color.Transparent;
			label22.Name = "label22";
			label21.BackColor = System.Drawing.Color.DimGray;
			label21.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			resources.ApplyResources(label21, "label21");
			label21.ForeColor = System.Drawing.Color.White;
			label21.Name = "label21";
			uiTabPageVersionCheck.Controls.Add(groupVersionChecks);
			uiTabPageVersionCheck.Controls.Add(label20);
			uiTabPageVersionCheck.Controls.Add(checkEnableVersionCheck);
			uiTabPageVersionCheck.Key = "VersionChecking";
			resources.ApplyResources(uiTabPageVersionCheck, "uiTabPageVersionCheck");
			uiTabPageVersionCheck.Name = "uiTabPageVersionCheck";
			uiTabPageVersionCheck.TabStop = true;
			resources.ApplyResources(groupVersionChecks, "groupVersionChecks");
			groupVersionChecks.BackColor = System.Drawing.Color.Transparent;
			groupVersionChecks.Controls.Add(lblEnableVersionUpgrade);
			groupVersionChecks.Controls.Add(checkSendUsageInformation);
			groupVersionChecks.Controls.Add(label7);
			groupVersionChecks.Controls.Add(checkEnableVersionUpgrade);
			groupVersionChecks.Controls.Add(numVersionCheckInterval);
			groupVersionChecks.Controls.Add(checkVersionCheckAtStartup);
			groupVersionChecks.Name = "groupVersionChecks";
			groupVersionChecks.TabStop = false;
			resources.ApplyResources(lblEnableVersionUpgrade, "lblEnableVersionUpgrade");
			lblEnableVersionUpgrade.ForeColor = System.Drawing.Color.Blue;
			lblEnableVersionUpgrade.Name = "lblEnableVersionUpgrade";
			resources.ApplyResources(checkSendUsageInformation, "checkSendUsageInformation");
			checkSendUsageInformation.BackColor = System.Drawing.Color.Transparent;
			checkSendUsageInformation.Checked = true;
			checkSendUsageInformation.CheckState = System.Windows.Forms.CheckState.Checked;
			checkSendUsageInformation.Name = "checkSendUsageInformation";
			checkSendUsageInformation.UseVisualStyleBackColor = true;
			resources.ApplyResources(label7, "label7");
			label7.BackColor = System.Drawing.Color.Transparent;
			label7.Name = "label7";
			resources.ApplyResources(checkEnableVersionUpgrade, "checkEnableVersionUpgrade");
			checkEnableVersionUpgrade.BackColor = System.Drawing.Color.Transparent;
			checkEnableVersionUpgrade.Checked = true;
			checkEnableVersionUpgrade.CheckState = System.Windows.Forms.CheckState.Checked;
			checkEnableVersionUpgrade.Name = "checkEnableVersionUpgrade";
			checkEnableVersionUpgrade.UseVisualStyleBackColor = true;
			resources.ApplyResources(numVersionCheckInterval, "numVersionCheckInterval");
			int[] tempAnotherLocal14 = new int[4];
			tempAnotherLocal14[0] = 0x5a0;
			numVersionCheckInterval.Maximum = new decimal(tempAnotherLocal14);
			numVersionCheckInterval.Name = "numVersionCheckInterval";
			resources.ApplyResources(checkVersionCheckAtStartup, "checkVersionCheckAtStartup");
			checkVersionCheckAtStartup.BackColor = System.Drawing.Color.Transparent;
			checkVersionCheckAtStartup.Checked = true;
			checkVersionCheckAtStartup.CheckState = System.Windows.Forms.CheckState.Checked;
			checkVersionCheckAtStartup.Name = "checkVersionCheckAtStartup";
			checkVersionCheckAtStartup.UseVisualStyleBackColor = true;
			label20.BackColor = System.Drawing.Color.DimGray;
			label20.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			resources.ApplyResources(label20, "label20");
			label20.ForeColor = System.Drawing.Color.White;
			label20.Name = "label20";
			resources.ApplyResources(checkEnableVersionCheck, "checkEnableVersionCheck");
			checkEnableVersionCheck.BackColor = System.Drawing.Color.Transparent;
			checkEnableVersionCheck.Checked = true;
			checkEnableVersionCheck.CheckState = System.Windows.Forms.CheckState.Checked;
			checkEnableVersionCheck.Name = "checkEnableVersionCheck";
			checkEnableVersionCheck.UseVisualStyleBackColor = true;
			checkEnableVersionCheck.CheckedChanged += checkEnableVersionCheck_CheckedChanged;
			panelBottom.Controls.Add(btnOK);
			panelBottom.Controls.Add(btnCancel);
			resources.ApplyResources(panelBottom, "panelBottom");
			panelBottom.Name = "panelBottom";
			resources.ApplyResources(treeView1, "treeView1");
			treeView1.FullRowSelect = true;
			treeView1.HideSelection = false;
			treeView1.HotTracking = true;
			treeView1.ItemHeight = 0x12;
			treeView1.Name = "treeView1";
			treeView1.Nodes.AddRange(new System.Windows.Forms.TreeNode[]
			{
				(System.Windows.Forms.TreeNode)resources.GetObject("treeView1.Nodes"), (System.Windows.Forms.TreeNode)resources.GetObject("treeView1.Nodes1"), (System.Windows.Forms.TreeNode)resources.GetObject("treeView1.Nodes2"), (System.Windows.Forms.TreeNode)resources.GetObject("treeView1.Nodes3"), (System.Windows.Forms.TreeNode)resources.GetObject("treeView1.Nodes4"), (System.Windows.Forms.TreeNode)resources.GetObject("treeView1.Nodes5"), (System.Windows.Forms.TreeNode)resources.GetObject("treeView1.Nodes6"), (System.Windows.Forms.TreeNode)resources.GetObject("treeView1.Nodes7")
			});
			treeView1.ShowRootLines = false;
			treeView1.AfterSelect += treeView1_AfterSelect;
			panelLeft.Controls.Add(panelRight);
			panelLeft.Controls.Add(treeView1);
			resources.ApplyResources(panelLeft, "panelLeft");
			panelLeft.Name = "panelLeft";
			panelRight.Controls.Add(uiTabs);
			resources.ApplyResources(panelRight, "panelRight");
			panelRight.Name = "panelRight";
			resources.ApplyResources(checkCommitIsAlwaysEnabled, "checkCommitIsAlwaysEnabled");
			checkCommitIsAlwaysEnabled.BackColor = System.Drawing.Color.Transparent;
			checkCommitIsAlwaysEnabled.Checked = true;
			checkCommitIsAlwaysEnabled.CheckState = System.Windows.Forms.CheckState.Checked;
			checkCommitIsAlwaysEnabled.Name = "checkCommitIsAlwaysEnabled";
			checkCommitIsAlwaysEnabled.UseVisualStyleBackColor = true;
			base.AcceptButton = btnOK;
			resources.ApplyResources(this, "$this");
			base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			base.CancelButton = btnCancel;
			base.Controls.Add(panelLeft);
			base.Controls.Add(panelBottom);
			base.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
			base.Name = "SettingsDialog";
			base.ShowInTaskbar = false;
			((System.ComponentModel.ISupportInitialize)uiTabs).EndInit();
			uiTabs.ResumeLayout(false);
			uiTabPageGeneral.ResumeLayout(false);
			uiTabPageGeneral.PerformLayout();
			uiTabPageDisplay.ResumeLayout(false);
			uiTabPageDisplay.PerformLayout();
			groupSourcesPanel.ResumeLayout(false);
			groupSourcesPanel.PerformLayout();
			numPreviewLines.EndInit();
			numPageSize.EndInit();
			uiTabPageOperation.ResumeLayout(false);
			uiTabPageOperation.PerformLayout();
			uiTabPageKeyboard.ResumeLayout(false);
			uiTabPageUpdates.ResumeLayout(false);
			uiTabPageUpdates.PerformLayout();
			numSecondsPerSource.EndInit();
			numUpdatesInterval.EndInit();
			uiTabPageTortoiseSVN.ResumeLayout(false);
			uiTabPageTortoiseSVN.PerformLayout();
			numSVNUpdateSourcesQueueTimeoutSeconds.EndInit();
			uiTabPageRecommending.ResumeLayout(false);
			uiGroupBoxRecommendMessage.ResumeLayout(false);
			uiGroupBoxRecommendMessage.PerformLayout();
			uiTabPageVersionCheck.ResumeLayout(false);
			uiTabPageVersionCheck.PerformLayout();
			groupVersionChecks.ResumeLayout(false);
			groupVersionChecks.PerformLayout();
			numVersionCheckInterval.EndInit();
			panelBottom.ResumeLayout(false);
			panelLeft.ResumeLayout(false);
			panelRight.ResumeLayout(false);
			base.ResumeLayout(false);
		}

		#endregion
		private System.Windows.Forms.Button btnCancel;
		private System.Windows.Forms.Button btnOK;
		private System.Windows.Forms.CheckBox checkAutomaticallyResolveTortoiseSVNProcess;
		private System.Windows.Forms.CheckBox checkAutomaticInterval;
		private System.Windows.Forms.CheckBox checkCommitIsAlwaysEnabled;
		private System.Windows.Forms.CheckBox checkDismissErrorsWhenClicked;
		private System.Windows.Forms.CheckBox checkEnableUpdates;
		private System.Windows.Forms.CheckBox checkEnableVersionCheck;
		private System.Windows.Forms.CheckBox checkEnableVersionUpgrade;
		private System.Windows.Forms.CheckBox checkHideWhenMinimized;
		private System.Windows.Forms.CheckBox checkIgnoreDisabledSourcesWhenUpdatingAll;
		private System.Windows.Forms.CheckBox checkIgnoreIgnoreOnCommit;
		private System.Windows.Forms.CheckBox checkIgnoreIgnoreOnCommitConflicts;
		private System.Windows.Forms.CheckBox checkMinimizeWhenClosing;
		private System.Windows.Forms.CheckBox checkPromptUpdateHeadRevision;
		private System.Windows.Forms.CheckBox checkPromptUpdateOldRevision;
		private System.Windows.Forms.CheckBox checkSendUsageInformation;
		private System.Windows.Forms.CheckBox checkShowDefaultTextInsteadOfEmptyLogMessage;
		private System.Windows.Forms.CheckBox checkSourcesPanelShowLastCheck;
		private System.Windows.Forms.CheckBox checkSourcesPanelShowNoUpdates;
		private System.Windows.Forms.CheckBox checkSourcesPanelShowPath;
		private System.Windows.Forms.CheckBox checkSourcesPanelShowUrl;
		private System.Windows.Forms.CheckBox checkStartMinimized;
		private System.Windows.Forms.CheckBox checkStartWithWindows;
		private System.Windows.Forms.CheckBox checkSVNUpdateSourcesParallel;
		private System.Windows.Forms.CheckBox checkTreatUnversionedAsModified;
		private System.Windows.Forms.CheckBox checkUnlimitedPageSize;
		private System.Windows.Forms.CheckBox checkVersionCheckAtStartup;
		private System.Windows.Forms.CheckBox checkWatchTheNetworkAvailability;
		private System.Windows.Forms.Button cmdTortoiseSVNSettings;
		private System.Windows.Forms.ComboBox comboAutoCloseTortoiseSVN;
		private System.Windows.Forms.ComboBox comboDefaultUserAction;
		private System.Windows.Forms.GroupBox groupSourcesPanel;
		private System.Windows.Forms.GroupBox groupVersionChecks;
		private SVNMonitor.View.Controls.KeyboardEditor keyboardEditor1;
		private System.Windows.Forms.Label label1;
		private System.Windows.Forms.Label label10;
		private System.Windows.Forms.Label label11;
		private System.Windows.Forms.Label label13;
		private System.Windows.Forms.Label label14;
		private System.Windows.Forms.Label label15;
		private System.Windows.Forms.Label label16;
		private System.Windows.Forms.Label label17;
		private System.Windows.Forms.Label label18;
		private System.Windows.Forms.Label label19;
		private System.Windows.Forms.Label label2;
		private System.Windows.Forms.Label label20;
		private System.Windows.Forms.Label label21;
		private System.Windows.Forms.Label label22;
		private System.Windows.Forms.Label label3;
		private System.Windows.Forms.Label label4;
		private System.Windows.Forms.Label label5;
		private System.Windows.Forms.Label label6;
		private System.Windows.Forms.Label label7;
		private System.Windows.Forms.Label label8;
		private System.Windows.Forms.Label label9;
		private System.Windows.Forms.Label lblEnableVersionUpgrade;
		private System.Windows.Forms.Label lblWatchTheNetworkAvailability;
		private System.Windows.Forms.LinkLabel linkAutoCheckTortoiseSVN;
		private System.Windows.Forms.LinkLabel linkTextEditorBrowse;
		private System.Windows.Forms.LinkLabel linkTortoiseEXEBrowse;
		private System.Windows.Forms.NumericUpDown numPageSize;
		private System.Windows.Forms.NumericUpDown numPreviewLines;
		private System.Windows.Forms.NumericUpDown numSecondsPerSource;
		private System.Windows.Forms.NumericUpDown numSVNUpdateSourcesQueueTimeoutSeconds;
		private System.Windows.Forms.NumericUpDown numUpdatesInterval;
		private System.Windows.Forms.NumericUpDown numVersionCheckInterval;
		private System.Windows.Forms.Panel panelBottom;
		private System.Windows.Forms.Panel panelLeft;
		private System.Windows.Forms.Panel panelRight;
		private System.Windows.Forms.TreeView treeView1;
		private System.Windows.Forms.TextBox txtRecommendMessage;
		private System.Windows.Forms.TextBox txtTextEditor;
		private System.Windows.Forms.TextBox txtTortoiseEXE;
		private System.Windows.Forms.GroupBox uiGroupBoxRecommendMessage;
		private Janus.Windows.UI.Tab.UITabPage uiTabPageDisplay;
		private Janus.Windows.UI.Tab.UITabPage uiTabPageGeneral;
		private Janus.Windows.UI.Tab.UITabPage uiTabPageKeyboard;
		private Janus.Windows.UI.Tab.UITabPage uiTabPageOperation;
		private Janus.Windows.UI.Tab.UITabPage uiTabPageRecommending;
		private Janus.Windows.UI.Tab.UITabPage uiTabPageTortoiseSVN;
		private Janus.Windows.UI.Tab.UITabPage uiTabPageUpdates;
		private Janus.Windows.UI.Tab.UITabPage uiTabPageVersionCheck;
		private Janus.Windows.UI.Tab.UITab uiTabs;
	}
}